# Generated by Django 4.2.15 on 2024-12-23 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_client_user_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('capacity', models.FloatField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance'), ('Idle', 'Idle')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WoodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wood_type', models.CharField(choices=[('Teak', 'Teak'), ('Rosewood', 'Rosewood')], max_length=50)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10)),
                ('quantity', models.FloatField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Processed', 'Processed')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_processed', models.FloatField()),
                ('processing_date', models.DateField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In-Progress', 'In-Progress'), ('Faulty', 'Faulty')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_logs_emp', to='accounts.employee')),
                ('processing_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs_processing_unit', to='core.processingunit')),
                ('wood_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs_wood_inventory', to='core.woodinventory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Operational', 'Operational'), ('Maintenance', 'Maintenance'), ('Non-functional', 'Non-functional')], max_length=20)),
                ('purchase_date', models.DateField()),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('processing_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machineries', to='core.processingunit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
