# Generated by Django 4.2.15 on 2025-03-19 14:38

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='woodinventory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.wood_inventory_storage),
        ),
    ]
