# Generated by Django 4.2.15 on 2025-05-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woodinventory',
            name='wood_type',
            field=models.CharField(choices=[('Teak', 'Teak'), ('Rosewood', 'Rosewood'), ('ໄມ້ປັກເກ້', 'ໄມ້ປັກເກ້'), ('ໄມ້ບົວ', 'ໄມ້ບົວ')], max_length=50),
        ),
    ]
