# Generated by Django 4.2.15 on 2025-05-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlog',
            name='quantity_processed',
            field=models.IntegerField(default=0),
        ),
    ]
