# Generated by Django 4.2.15 on 2025-06-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_productionlog_quantity_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woodinventory',
            name='wood_type',
            field=models.CharField(choices=[('ໄມ້ສັກ', 'ໄມ່ສັກ'), ('ໄມ້ດູ່', 'ໄມ້ດູ່'), ('ໄມ້ປັກເກ້', 'ໄມ້ປັກເກ້'), ('ໄມ້ບົວ', 'ໄມ້ບົວ')], max_length=50),
        ),
    ]
