# Generated by Django 4.2.15 on 2025-06-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_woodinventory_wood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='status',
            field=models.CharField(choices=[('Operational', 'ພ້ອມໃຊ້ງານ'), ('Maintenance', 'ບຳລຸງຮັກສາ'), ('Non-functional', 'ໃຊ້ງານບໍໄດ້')], max_length=20),
        ),
        migrations.AlterField(
            model_name='processingunit',
            name='status',
            field=models.CharField(choices=[('Active', 'ໃຊ້ງານ'), ('Maintenance', 'ບຳລຸງຮັກສາ'), ('Idle', 'ບໍໄດ້ໃຊ້ງານ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='status',
            field=models.CharField(choices=[('Completed', 'ສຳເລັດແລ້ວ'), ('In-Progress', 'ກຳລັງດຳເນີນການ'), ('Faulty', 'ລົ້ມເຫຼວ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='woodinventory',
            name='status',
            field=models.CharField(choices=[('Available', 'ຫວ່າງ'), ('Reserved', 'ຈອງ'), ('Processed', 'ດຳເນິນການແລ້ວ')], max_length=20),
        ),
    ]
